In [11]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [38]:
%autoreload 3

In [39]:
import torch as th
import nn 
import numpy as np
import operations

In [40]:
inputs = th.rand((5, 3), requires_grad=True)

In [41]:
linear = nn.HyperbolicLinearLinear(3, 2, False)

In [42]:
linear(inputs)

RuntimeError: size mismatch, m1: [3 x 2], m2: [5 x 3] at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/TH/generic/THTensorMath.cpp:940

In [30]:
linear.W.t() @ inputs.t()

tensor([[0.1098, 0.6707, 0.3642, 0.8170, 0.9051],
        [0.1316, 0.9863, 0.5586, 1.2483, 1.3112]], grad_fn=<MmBackward>)

In [32]:
(inputs @ linear.W)

tensor([[0.1098, 0.1316],
        [0.6707, 0.9863],
        [0.3642, 0.5586],
        [0.8170, 1.2483],
        [0.9051, 1.3112]], grad_fn=<MmBackward>)

In [18]:
operations.mat_mult(linear.W, inputs.transpose(-1, 0))

RuntimeError: size mismatch, m1: [3 x 2], m2: [3 x 5] at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/TH/generic/THTensorMath.cpp:940

In [19]:
th.mm(linear.W, inputs)

RuntimeError: size mismatch, m1: [3 x 2], m2: [5 x 3] at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/TH/generic/THTensorMath.cpp:940

In [20]:
inputs @ linear.W

tensor([[0.2290, 0.3085],
        [1.0144, 0.9801],
        [0.4811, 0.3963],
        [1.3384, 1.1666],
        [1.5451, 1.5580]], grad_fn=<MmBackward>)